### ISSUE TITLE
using first time

### ISSUE THREAD

**Issue by napestershine** [php-earth/stats#74]
Getting following error
Retrieving members from API page 1
 40/40 [============================] 100% 4 secs/4 secs 6.0 MiB

PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in C                                                                              :\xampp\htdocs\one\stats\src\Util\Merger.php:32
Stack trace:
#0 C:\xampp\htdocs\one\stats\src\Collection\CommentCollection.php(25): PhpEarth\                                                                              Stats\Util\Merger->getMergedItems('636561533213356')
#1 C:\xampp\htdocs\one\stats\src\Model\User.php(177): PhpEarth\Stats\Collection\                                                                              CommentCollection->getMergedCommentsByUserId('636561533213356')
#2 C:\xampp\htdocs\one\stats\vendor\twig\twig\lib\Twig\Extension\Core.php(1595):                                                                               PhpEarth\Stats\Model\User->getPointsCount()
#3 C:\xampp\htdocs\one\stats\vendor\twig\twig\lib\Twig\Environment.php(378) : ev                                                                              al()'d code(40): twig_get_attribute(Object(Twig_Environment), Object(Twig_Source                                                                              ), Object(PhpEarth\Stats\Model\User), 'getPointsCount', Array, 'method')
#4 C:\xampp\htdocs\one\stats\vendor\twig\twig\lib\Twig\Template.php(389): __Twig                                                                              Template_2c779e2ca0a83267837b29ed17688a9aaacebe558f2c45a8e83c3ff935fac9fc->doDis                                                                              play(Array, Array)
#5 C:\xampp\htdocs\one\stats\vendor\twig\twig\lib\Twig\Template.php(366): Twig_T                                                                              emplate in C:\xampp\htdocs\one\stats\src\Util\Merger.php on line 32

**Comment by petk** [comment]
Hello @napestershine 

To generate the stats you need to have the following:
- Facebook application like mentioned [here](https://github.com/php-earth/stats/blob/master/docs/installation.md)
- Open group
- or closed group where you're administrator. Closed and secret groups require administrator access.
- install the stats using composer on the latest stable PHP
- And the configuration file for your FB application:
```yaml
# config/parameters.yml
parameters:
    fb_app_id: xxx
    fb_app_secret: yyy
    default_graph_version: v2.11
    group_id: 2204685680
    locale: en
    top_users_count: 5
    last_blocked_count: 0
    new_blocked_count: 0
    api_pages: 10
    top_topics:
        -
            title: '20 years of PHP'
            url: fb.com/groups/2204685680/permalink/10153439277470681
    ignored_users: {  }
    admins: {  }
    offset: 259200
```
